# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='save',
        ),
    ]
